spring.application.name=application-service

# App Configuration
app.api-version=v1
server.port=0

# Set active profile to 'dev'
spring.profiles.active=dev

#  Use SNAKE_CASE for JSON properties
spring.jackson.property-naming-strategy=SNAKE_CASE

#Postgres DB
spring.datasource.url=jdbc:postgresql://localhost:5433/appdb
spring.datasource.username=dummyuser
spring.datasource.password=dummypassword
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# output:
spring.output.ansi.enabled: ALWAYS

# Eruka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
