spring.application.name=application-service
# add version value to be used in @RequestMapping
app.api-version=v1

# Server Port
server.port=0

#Postgres DB
spring.datasource.url=jdbc:postgresql://localhost:5433/appdb
spring.datasource.username=dummyuser
spring.datasource.password=dummypassword
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# output:
spring.output.ansi.enabled: ALWAYS

# Eruka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
