spring.application.name=Application-service

#Postgres DB
spring.datasource.url=jdbc:postgresql://localhost:5433/appdb
spring.datasource.username=dummyuser
spring.datasource.password=dummypassword
spring.jpa.hibernate.ddl-auto=update

# output:
spring.output.ansi.enabled: ALWAYS